version: '3.8'
services:
  user_postgres:
    image: postgres:13
    container_name: user_postgres
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "false"
      KC_LOG_LEVEL: info
    command: ["start-dev", "--http-port", "8080"]
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/var/lib/keycloak/data

volumes:
  keycloak_data: